// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearAllLocalData() {
  return window['go']['main']['App']['ClearAllLocalData']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetImageBase64(arg1) {
  return window['go']['main']['App']['GetImageBase64'](arg1);
}

export function GetLogsByDate(arg1) {
  return window['go']['main']['App']['GetLogsByDate'](arg1);
}

export function GetStats(arg1) {
  return window['go']['main']['App']['GetStats'](arg1);
}

export function GetTodayLogs() {
  return window['go']['main']['App']['GetTodayLogs']();
}

export function OpenTrackerWizard(arg1) {
  return window['go']['main']['App']['OpenTrackerWizard'](arg1);
}

export function ProcessPendingLogs() {
  return window['go']['main']['App']['ProcessPendingLogs']();
}

export function RecordInputActivity(arg1, arg2) {
  return window['go']['main']['App']['RecordInputActivity'](arg1, arg2);
}

export function SetAuthSession(arg1, arg2) {
  return window['go']['main']['App']['SetAuthSession'](arg1, arg2);
}

export function SetOrgGeminiKey(arg1, arg2) {
  return window['go']['main']['App']['SetOrgGeminiKey'](arg1, arg2);
}

export function SetUserPersonalKey(arg1) {
  return window['go']['main']['App']['SetUserPersonalKey'](arg1);
}

export function TriggerSyncNow() {
  return window['go']['main']['App']['TriggerSyncNow']();
}

export function UpdateAIModel(arg1) {
  return window['go']['main']['App']['UpdateAIModel'](arg1);
}

export function UpdateGeminiAPIKey(arg1) {
  return window['go']['main']['App']['UpdateGeminiAPIKey'](arg1);
}

export function UpdateScreenshotInterval(arg1) {
  return window['go']['main']['App']['UpdateScreenshotInterval'](arg1);
}
