// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetImageBase64(arg1) {
  return window['go']['main']['App']['GetImageBase64'](arg1);
}

export function GetLogsByDate(arg1) {
  return window['go']['main']['App']['GetLogsByDate'](arg1);
}

export function GetStats(arg1) {
  return window['go']['main']['App']['GetStats'](arg1);
}

export function GetTodayLogs() {
  return window['go']['main']['App']['GetTodayLogs']();
}

export function ProcessPendingLogs() {
  return window['go']['main']['App']['ProcessPendingLogs']();
}

export function UpdateGeminiAPIKey(arg1) {
  return window['go']['main']['App']['UpdateGeminiAPIKey'](arg1);
}
