// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {db} from '../models';

export function ClearAllLocalData():Promise<boolean>;

export function GetConfig():Promise<Record<string, any>>;

export function GetImageBase64(arg1:string):Promise<string>;

export function GetLogsByDate(arg1:string):Promise<Array<db.LogEntry>>;

export function GetStats(arg1:string):Promise<db.ProductivityStats>;

export function GetTodayLogs():Promise<Array<db.LogEntry>>;

export function ProcessPendingLogs():Promise<number>;

export function RecordInputActivity(arg1:number,arg2:number):Promise<void>;

export function UpdateAIModel(arg1:string):Promise<boolean>;

export function UpdateGeminiAPIKey(arg1:string):Promise<boolean>;
